FROM debian:bookworm-slim

ARG TARGETARCH

RUN apt-get update && apt-get install -y \
    ca-certificates \
    netcat-openbsd \
    && rm -rf /var/lib/apt/lists/*

COPY dist/${TARGETARCH}/tron /app/tron

WORKDIR /data
ENTRYPOINT ["/app/tron"]
