use serde::{Deserialize, Serialize};
use std::hash::Hash;

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, Hash)]
pub enum Achievements {
    // Miners
    MinerI,
    MinerII,
    MinerIII,
    MinerIV,
    MinerV,
    MinerVI,
    MinerVII,
    MinerVIII,
    MinerIX,
    MinerX,
    MinerXI,
    MinerXII,
    MinerXIII,
    MinerXIV,
    MinerXV,
    MinerXVI,
    MinerXVII,
    MinerXVIII,
    MinerXIX,
    MinerXX,

    // Warrior
    WarriorI,
    WarriorII,
    WarriorIII,
    WarriorIV,
    WarriorV,
    WarriorVI,
    WarriorVII,
    WarriorVIII,
    WarriorIX,
    WarriorX,
    WarriorXI,
    WarriorXII,
    WarriorXIII,
    WarriorXIV,
    WarriorXV,
    WarriorXVI,
    WarriorXVII,
    WarriorXVIII,
    WarriorXIX,
    WarriorXX,

    // Builder
    BuilderI,
    BuilderII,
    BuilderIII,
    BuilderIV,
    BuilderV,
    BuilderVI,
    BuilderVII,
    BuilderVIII,
    BuilderIX,
    BuilderX,
    BuilderXI,
    BuilderXII,
    BuilderXIII,
    BuilderXIV,
    BuilderXV,
    BuilderXVI,
    BuilderXVII,
    BuilderXVIII,
    BuilderXIX,
    BuilderXX,
}
