use serde::{Deserialize, Serialize};
use std::hash::Hash;

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, Hash)]
pub enum Achievements {
    // Miners
    MinerI,
    MinerII,
    MinerIII,
    MinerIV,
    MinerV,
    MinerVI,
    MinerVII,
    MinerVIII,
    MinerIX,
    MinerX,
    MinerXI,
    MinerXII,
    MinerXIII,
    MinerXIV,
    MinerXV,
    MinerXVI,
    MinerXVII,
    MinerXVIII,
    MinerXIX,
    MinerXX,

    // Warrior
    WarriorI,
    WarriorII,
    WarriorIII,
    WarriorIV,
    WarriorV,
    WarriorVI,
    WarriorVII,
    WarriorVIII,
    WarriorIX,
    WarriorX,
    WarriorXI,
    WarriorXII,
    WarriorXIII,
    WarriorXIV,
    WarriorXV,
    WarriorXVI,
    WarriorXVII,
    WarriorXVIII,
    WarriorXIX,
    WarriorXX,

    // Builder
    BuilderI,
    BuilderII,
    BuilderIII,
    BuilderIV,
    BuilderV,
    BuilderVI,
    BuilderVII,
    BuilderVIII,
    BuilderIX,
    BuilderX,
    BuilderXI,
    BuilderXII,
    BuilderXIII,
    BuilderXIV,
    BuilderXV,
    BuilderXVI,
    BuilderXVII,
    BuilderXVIII,
    BuilderXIX,
    BuilderXX,
}

impl Achievements {
    pub fn warrior_for_kills(kills: u64) -> Option<Achievements> {
        match kills {
            10 => Some(Achievements::WarriorI),
            25 => Some(Achievements::WarriorII),
            50 => Some(Achievements::WarriorIII),
            100 => Some(Achievements::WarriorIV),
            250 => Some(Achievements::WarriorV),
            500 => Some(Achievements::WarriorVI),
            1_000 => Some(Achievements::WarriorVII),
            2_000 => Some(Achievements::WarriorVIII),
            3_000 => Some(Achievements::WarriorIX),
            4_000 => Some(Achievements::WarriorX),
            5_000 => Some(Achievements::WarriorXI),
            6_000 => Some(Achievements::WarriorXII),
            7_000 => Some(Achievements::WarriorXIII),
            8_000 => Some(Achievements::WarriorXIV),
            9_000 => Some(Achievements::WarriorXV),
            10_000 => Some(Achievements::WarriorXVI),
            15_000 => Some(Achievements::WarriorXVII),
            20_000 => Some(Achievements::WarriorXVIII),
            25_000 => Some(Achievements::WarriorXIX),
            30_000 => Some(Achievements::WarriorXX),
            _ => None,
        }
    }

    pub fn miner_for_block_broken(block_broken: u64) -> Option<Achievements> {
        match block_broken {
            50 => Some(Achievements::MinerI),
            100 => Some(Achievements::MinerII),
            500 => Some(Achievements::MinerIII),
            1_000 => Some(Achievements::MinerIV),
            5_000 => Some(Achievements::MinerV),
            10_000 => Some(Achievements::MinerVI),
            25_000 => Some(Achievements::MinerVII),
            50_000 => Some(Achievements::MinerVIII),
            75_000 => Some(Achievements::MinerIX),
            100_000 => Some(Achievements::MinerX),
            250_000 => Some(Achievements::MinerXI),
            500_000 => Some(Achievements::MinerXII),
            750_000 => Some(Achievements::MinerXIII),
            1_000_000 => Some(Achievements::MinerXIV),
            1_500_000 => Some(Achievements::MinerXV),
            2_000_000 => Some(Achievements::MinerXVI),
            2_500_000 => Some(Achievements::MinerXVII),
            3_000_000 => Some(Achievements::MinerXVIII),
            4_000_000 => Some(Achievements::MinerXIX),
            5_000_000 => Some(Achievements::MinerXX),
            _ => None,
        }
    }

    pub fn builder_for_blocks_placed(blocks_placed: u64) -> Option<Achievements> {
        match blocks_placed {
            50 => Some(Achievements::BuilderI),
            100 => Some(Achievements::BuilderII),
            500 => Some(Achievements::BuilderIII),
            1_000 => Some(Achievements::BuilderIV),
            2_500 => Some(Achievements::BuilderV),
            5_000 => Some(Achievements::BuilderVI),
            10_000 => Some(Achievements::BuilderVII),
            25_000 => Some(Achievements::BuilderVIII),
            50_000 => Some(Achievements::BuilderIX),
            75_000 => Some(Achievements::BuilderX),
            100_000 => Some(Achievements::BuilderXI),
            250_000 => Some(Achievements::BuilderXII),
            500_000 => Some(Achievements::BuilderXIII),
            750_000 => Some(Achievements::BuilderXIV),
            1_000_000 => Some(Achievements::BuilderXV),
            1_500_000 => Some(Achievements::BuilderXVI),
            2_000_000 => Some(Achievements::BuilderXVII),
            2_500_000 => Some(Achievements::BuilderXVIII),
            3_000_000 => Some(Achievements::BuilderXIX),
            4_000_000 => Some(Achievements::BuilderXX),
            _ => None,
        }
    }

    pub fn reward(achievements: Achievements) -> u64 {
        match achievements {
            Achievements::BuilderI => 100,
            Achievements::BuilderII => 200,
            Achievements::BuilderIII => 300,
            Achievements::BuilderIV => 400,
            Achievements::BuilderV => 500,
            Achievements::BuilderVI => 600,
            Achievements::BuilderVII => 700,
            Achievements::BuilderVIII => 800,
            Achievements::BuilderIX => 900,
            Achievements::BuilderX => 1000,
            Achievements::BuilderXI => 1100,
            Achievements::BuilderXII => 1200,
            Achievements::BuilderXIII => 1300,
            Achievements::BuilderXIV => 1400,
            Achievements::BuilderXV => 1500,
            Achievements::BuilderXVI => 1600,
            Achievements::BuilderXVII => 1700,
            Achievements::BuilderXVIII => 1800,
            Achievements::BuilderXIX => 1900,
            Achievements::BuilderXX => 2000,
            Achievements::MinerI => 100,
            Achievements::MinerII => 200,
            Achievements::MinerIII => 300,
            Achievements::MinerIV => 400,
            Achievements::MinerV => 500,
            Achievements::MinerVI => 600,
            Achievements::MinerVII => 700,
            Achievements::MinerVIII => 800,
            Achievements::MinerIX => 900,
            Achievements::MinerX => 1000,
            Achievements::MinerXI => 1100,
            Achievements::MinerXII => 1200,
            Achievements::MinerXIII => 1300,
            Achievements::MinerXIV => 1400,
            Achievements::MinerXV => 1500,
            Achievements::MinerXVI => 1600,
            Achievements::MinerXVII => 1700,
            Achievements::MinerXVIII => 1800,
            Achievements::MinerXIX => 1900,
            Achievements::MinerXX => 2000,
            Achievements::WarriorI => 100,
            Achievements::WarriorII => 200,
            Achievements::WarriorIII => 300,
            Achievements::WarriorIV => 400,
            Achievements::WarriorV => 500,
            Achievements::WarriorVI => 600,
            Achievements::WarriorVII => 700,
            Achievements::WarriorVIII => 800,
            Achievements::WarriorIX => 900,
            Achievements::WarriorX => 1000,
            Achievements::WarriorXI => 1100,
            Achievements::WarriorXII => 1200,
            Achievements::WarriorXIII => 1300,
            Achievements::WarriorXIV => 1400,
            Achievements::WarriorXV => 1500,
            Achievements::WarriorXVI => 1600,
            Achievements::WarriorXVII => 1700,
            Achievements::WarriorXVIII => 1800,
            Achievements::WarriorXIX => 1900,
            Achievements::WarriorXX => 2000,
        }
    }
}
